"""
LangGraph node functions for the RAG workflow.
Each node represents a step in the multi-agent pipeline.
"""

from typing import Any, Dict, List
from loguru import logger

from core.models import AgentState, ExtractedDocument, ExtractionResult
from agents import PDFExtractionAgent, ContextConstructionAgent, ResearchSynthesisAgent


def extraction_node(state: AgentState) -> AgentState:
    """
    Node 1: PDF Extraction (Docling)
    
    Extracts content from PDF files and converts to raw Markdown.
    Uses ONLY Docling - no other extraction method.
    
    Args:
        state: Current workflow state with pdf_paths
        
    Returns:
        Updated state with extraction_results and markdown_files
    """
    logger.info("=== Extraction Node (Docling) ===")
    
    pdf_paths = state.get("pdf_paths", [])
    
    if not pdf_paths:
        logger.warning("No PDF paths provided")
        state["errors"] = state.get("errors", []) + ["No PDF paths provided"]
        return state
    
    try:
        agent = PDFExtractionAgent()
        extraction_results = agent.process(pdf_paths)
        
        # Store extraction results
        state["extraction_results"] = extraction_results
        state["markdown_files"] = [
            str(agent.output_dir / f"{r.source_file.replace('.pdf', '.md')}")
            for r in extraction_results if r.success
        ]
        state["current_agent"] = "PDFExtractionAgent"
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["extraction"] = "completed"
        
        successful = [r for r in extraction_results if r.success]
        logger.info(f"Extraction complete: {len(successful)}/{len(extraction_results)} documents processed")
        
    except Exception as e:
        logger.error(f"Extraction failed: {e}")
        state["errors"] = state.get("errors", []) + [f"Extraction error: {str(e)}"]
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["extraction"] = "failed"
    
    return state


def context_construction_node(state: AgentState) -> AgentState:
    """
    Node 2: Context Construction
    
    Parses Markdown files (generated by Docling), computes embeddings, 
    and stores in vector database.
    
    Args:
        state: Current workflow state with markdown_files from Agent 1
        
    Returns:
        Updated state with chunks and vector_store_ready flag
    """
    logger.info("=== Context Construction Node ===")
    
    markdown_files = state.get("markdown_files", [])
    extraction_results = state.get("extraction_results", [])
    
    if not markdown_files and not extraction_results:
        logger.warning("No markdown files available from extraction")
        state["errors"] = state.get("errors", []) + ["No documents to process"]
        return state
    
    try:
        agent = ContextConstructionAgent()
        
        # If we have extraction results, use them directly
        if extraction_results:
            # Pass the raw markdown content from Docling extraction
            result = agent.process_markdown_content(extraction_results)
        else:
            # Fallback to reading markdown files
            result = agent.process_markdown_files(markdown_files)
        
        state["chunks"] = result["chunks"]
        state["embeddings_stored"] = True
        state["vector_store_ready"] = True
        state["current_agent"] = "ContextConstructionAgent"
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["context_construction"] = "completed"
        
        # Store agent reference for later use
        state["_context_agent"] = agent
        
        logger.info(f"Context construction complete: {len(result['chunks'])} chunks stored")
        
    except Exception as e:
        logger.error(f"Context construction failed: {e}")
        state["errors"] = state.get("errors", []) + [f"Context construction error: {str(e)}"]
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["context_construction"] = "failed"
    
    return state


def search_node(state: AgentState) -> AgentState:
    """
    Node 3a: Search
    
    Performs hybrid search to find relevant passages.
    
    Args:
        state: Current workflow state with query and chunks
        
    Returns:
        Updated state with search_results
    """
    logger.info("=== Search Node ===")
    
    query = state.get("query")
    chunks = state.get("chunks", [])
    
    if not query:
        logger.warning("No query provided")
        state["errors"] = state.get("errors", []) + ["No query provided"]
        return state
    
    if not chunks:
        logger.warning("No chunks available for search")
        state["errors"] = state.get("errors", []) + ["No chunks available"]
        return state
    
    try:
        # Get or create context agent
        context_agent = state.get("_context_agent")
        llm_service_type = state.get("llm_service_type", "ollama")
        
        agent = ResearchSynthesisAgent(
            context_agent=context_agent,
            llm_service_type=llm_service_type
        )
        agent.prepare(chunks=chunks)
        
        # Perform search only
        search_results = agent._search(query)
        
        state["search_results"] = search_results
        state["current_agent"] = "ResearchSynthesisAgent"
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["search"] = "completed"
        
        # Store agent for synthesis
        state["_synthesis_agent"] = agent
        
        logger.info(f"Search complete: {len(search_results)} results found")
        
    except Exception as e:
        logger.error(f"Search failed: {e}")
        state["errors"] = state.get("errors", []) + [f"Search error: {str(e)}"]
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["search"] = "failed"
    
    return state


def synthesis_node(state: AgentState) -> AgentState:
    """
    Node 3b: Synthesis
    
    Synthesizes answer from search results using LLM.
    
    Args:
        state: Current workflow state with search_results and query
        
    Returns:
        Updated state with synthesis result
    """
    logger.info("=== Synthesis Node ===")
    
    query = state.get("query")
    search_results = state.get("search_results", [])
    
    if not query or not search_results:
        logger.warning("Missing query or search results")
        state["errors"] = state.get("errors", []) + ["Missing query or search results"]
        return state
    
    try:
        # Get the synthesis agent from state or create new
        agent = state.get("_synthesis_agent")
        
        if not agent:
            chunks = state.get("chunks", [])
            llm_service_type = state.get("llm_service_type", "ollama")
            agent = ResearchSynthesisAgent(llm_service_type=llm_service_type)
            agent.prepare(chunks=chunks)
        
        # Perform synthesis
        result = agent.process(query)
        
        state["synthesis"] = result
        state["current_agent"] = "ResearchSynthesisAgent"
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["synthesis"] = "completed"
        
        logger.info(f"Synthesis complete: confidence {result.confidence}")
        
    except Exception as e:
        logger.error(f"Synthesis failed: {e}")
        state["errors"] = state.get("errors", []) + [f"Synthesis error: {str(e)}"]
        state["processing_status"] = state.get("processing_status", {})
        state["processing_status"]["synthesis"] = "failed"
    
    return state


def should_continue_to_search(state: AgentState) -> str:
    """
    Conditional edge: Decide if we should proceed to search.
    
    Args:
        state: Current workflow state
        
    Returns:
        Next node name ('search' or 'end')
    """
    if state.get("query") and state.get("vector_store_ready"):
        return "search"
    return "end"


def should_continue_to_synthesis(state: AgentState) -> str:
    """
    Conditional edge: Decide if we should proceed to synthesis.
    
    Args:
        state: Current workflow state
        
    Returns:
        Next node name ('synthesis' or 'end')
    """
    if state.get("search_results"):
        return "synthesis"
    return "end"
